import type { OptionsState, SelectOption } from "@/types/transcription";

export const languageItems: SelectOption[] = [
  { label: "自動偵測", value: "auto" },
  { label: "繁體中文 / Chinese", value: "Chinese" },
  { label: "English", value: "English" },
  { label: "粵語 / Cantonese", value: "Cantonese" },
  { label: "阿拉伯文 / Arabic", value: "Arabic" },
  { label: "德文 / German", value: "German" },
  { label: "法文 / French", value: "French" },
  { label: "西班牙文 / Spanish", value: "Spanish" },
  { label: "葡萄牙文 / Portuguese", value: "Portuguese" },
  { label: "印尼文 / Indonesian", value: "Indonesian" },
  { label: "義大利文 / Italian", value: "Italian" },
  { label: "韓文 / Korean", value: "Korean" },
  { label: "俄文 / Russian", value: "Russian" },
  { label: "泰文 / Thai", value: "Thai" },
  { label: "越南文 / Vietnamese", value: "Vietnamese" },
  { label: "日文 / Japanese", value: "Japanese" },
  { label: "土耳其文 / Turkish", value: "Turkish" },
  { label: "印地文 / Hindi", value: "Hindi" },
  { label: "馬來文 / Malay", value: "Malay" },
  { label: "荷蘭文 / Dutch", value: "Dutch" },
  { label: "瑞典文 / Swedish", value: "Swedish" },
  { label: "丹麥文 / Danish", value: "Danish" },
  { label: "芬蘭文 / Finnish", value: "Finnish" },
  { label: "波蘭文 / Polish", value: "Polish" },
  { label: "捷克文 / Czech", value: "Czech" },
  { label: "菲律賓文 / Filipino", value: "Filipino" },
  { label: "波斯文 / Persian", value: "Persian" },
  { label: "希臘文 / Greek", value: "Greek" },
  { label: "匈牙利文 / Hungarian", value: "Hungarian" },
  { label: "馬其頓文 / Macedonian", value: "Macedonian" },
  { label: "羅馬尼亞文 / Romanian", value: "Romanian" },
  { label: "安徽方言 / Anhui", value: "Anhui" },
  { label: "東北方言 / Dongbei", value: "Dongbei" },
  { label: "福建方言 / Fujian", value: "Fujian" },
  { label: "甘肅方言 / Gansu", value: "Gansu" },
  { label: "貴州方言 / Guizhou", value: "Guizhou" },
  { label: "河北方言 / Hebei", value: "Hebei" },
  { label: "河南方言 / Henan", value: "Henan" },
  { label: "湖北方言 / Hubei", value: "Hubei" },
  { label: "湖南方言 / Hunan", value: "Hunan" },
  { label: "江西方言 / Jiangxi", value: "Jiangxi" },
  { label: "寧夏方言 / Ningxia", value: "Ningxia" },
  { label: "山東方言 / Shandong", value: "Shandong" },
  { label: "陝西方言 / Shaanxi", value: "Shaanxi" },
  { label: "山西方言 / Shanxi", value: "Shanxi" },
  { label: "四川方言 / Sichuan", value: "Sichuan" },
  { label: "天津方言 / Tianjin", value: "Tianjin" },
  { label: "雲南方言 / Yunnan", value: "Yunnan" },
  { label: "浙江方言 / Zhejiang", value: "Zhejiang" },
  {
    label: "粵語（香港口音） / Cantonese (Hong Kong accent)",
    value: "Cantonese (Hong Kong accent)",
  },
  {
    label: "粵語（廣東口音） / Cantonese (Guangdong accent)",
    value: "Cantonese (Guangdong accent)",
  },
  { label: "吳語 / Wu language", value: "Wu language" },
  { label: "閩南語 / Minnan language", value: "Minnan language" },
];

export const audioFilters = [
  {
    name: "Audio and video",
    extensions: [
      "wav",
      "mp3",
      "m4a",
      "aac",
      "flac",
      "ogg",
      "mp4",
      "mov",
      "mkv",
      "webm",
    ],
  },
];

export const defaultOptions: OptionsState = {
  language: "auto",
  writeSrt: true,
};
